ref: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [19]:
import numpy as np
a = np.asarray([100, 100, 255, 255]); a; a.shape
a_2D = np.stack([a]*2, axis=1); a_2D; a_2D.shape
a_2D = np.stack([a]*2, axis=0); a_2D; a_2D.shape

array([100, 100, 255, 255])

(4,)

array([[100, 100],
       [100, 100],
       [255, 255],
       [255, 255]])

(4, 2)

array([[100, 100, 255, 255],
       [100, 100, 255, 255]])

(2, 4)

In [22]:
import numpy as np
a = np.asarray([0, 0, 255, 255]); a; a.shape
a_3D = np.dstack((a,a,a)); a_3D; a_3D.shape

array([  0,   0, 255, 255])

(4,)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [255, 255, 255],
        [255, 255, 255]]])

(1, 4, 3)

## Array to Boolean

In [26]:
a
a_bool = a==0
a_bool

array([  0,   0, 255, 255])

array([ True,  True, False, False], dtype=bool)

## Reorder numpy array

In [8]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [12]:
import numpy as np
np.random.seed(8)
a = np.random.rand(3,2,4); a.shape; a

(3, 2, 4)

array([[[0.8734294 , 0.96854066, 0.86919454, 0.53085569],
        [0.23272833, 0.0113988 , 0.43046882, 0.40235136]],

       [[0.52267467, 0.4783918 , 0.55535647, 0.54338602],
        [0.76089558, 0.71237457, 0.6196821 , 0.42609177]],

       [[0.28907503, 0.97385524, 0.33377405, 0.21880106],
        [0.06580839, 0.98287055, 0.12785571, 0.32213079]]])

In [13]:
a = a[:,:,::-1]; a

array([[[0.53085569, 0.86919454, 0.96854066, 0.8734294 ],
        [0.40235136, 0.43046882, 0.0113988 , 0.23272833]],

       [[0.54338602, 0.55535647, 0.4783918 , 0.52267467],
        [0.42609177, 0.6196821 , 0.71237457, 0.76089558]],

       [[0.21880106, 0.33377405, 0.97385524, 0.28907503],
        [0.32213079, 0.12785571, 0.98287055, 0.06580839]]])

In [34]:
b = np.random.randint(5, size=(3,2,4)); b.shape; b

(3, 2, 4)

array([[[1, 0, 0, 4],
        [2, 1, 4, 0]],

       [[1, 1, 1, 4],
        [0, 3, 2, 3]],

       [[1, 1, 1, 1],
        [1, 1, 4, 0]]])

In [35]:
b1 = b[:,:,::-1]; b1.shape; b1

(3, 2, 4)

array([[[4, 0, 0, 1],
        [0, 4, 1, 2]],

       [[4, 1, 1, 1],
        [3, 2, 3, 0]],

       [[1, 1, 1, 1],
        [0, 4, 1, 1]]])

In [36]:
b2 = b[:,::-1,:]; b2.shape; b2

(3, 2, 4)

array([[[2, 1, 4, 0],
        [1, 0, 0, 4]],

       [[0, 3, 2, 3],
        [1, 1, 1, 4]],

       [[1, 1, 4, 0],
        [1, 1, 1, 1]]])

In [37]:
b3 = b[::-1,:,:]; b3.shape; b3

(3, 2, 4)

array([[[1, 1, 1, 1],
        [1, 1, 4, 0]],

       [[1, 1, 1, 4],
        [0, 3, 2, 3]],

       [[1, 0, 0, 4],
        [2, 1, 4, 0]]])