In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [19]:
import numpy as np
a = np.asarray([100, 100, 255, 255]); a; a.shape
a_2D = np.stack([a]*2, axis=1); a_2D; a_2D.shape
a_2D = np.stack([a]*2, axis=0); a_2D; a_2D.shape

array([100, 100, 255, 255])

(4,)

array([[100, 100],
       [100, 100],
       [255, 255],
       [255, 255]])

(4, 2)

array([[100, 100, 255, 255],
       [100, 100, 255, 255]])

(2, 4)

In [22]:
import numpy as np
a = np.asarray([0, 0, 255, 255]); a; a.shape
a_3D = np.dstack((a,a,a)); a_3D; a_3D.shape

array([  0,   0, 255, 255])

(4,)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [255, 255, 255],
        [255, 255, 255]]])

(1, 4, 3)

## Array to Boolean

In [26]:
a
a_bool = a==0
a_bool

array([  0,   0, 255, 255])

array([ True,  True, False, False], dtype=bool)