In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import scipy
from scipy.spatial.distance import pdist, squareform
condensed_idx = lambda i,j,n: i*n + j - i*(i+1)/2 - i - 1
n = 5
dim = 2
x = scipy.random.uniform(size = n*dim).reshape((n, dim)); x
d = pdist(x); d
ds = squareform(d); ds
for i in range(1, n-1):
    for j in range(i+1, n):
        assert ds[i, j] == d[int(condensed_idx(i, j, n))]

array([[0.93678689, 0.94529152],
       [0.07102766, 0.65414838],
       [0.90364841, 0.15844791],
       [0.23408577, 0.25379228],
       [0.55830939, 0.67135921]])

array([0.91340208, 0.78754113, 0.98588035, 0.46720887, 0.96900788,
       0.43228805, 0.48758557, 0.676317  , 0.61833409, 0.52866161])

array([[0.        , 0.91340208, 0.78754113, 0.98588035, 0.46720887],
       [0.91340208, 0.        , 0.96900788, 0.43228805, 0.48758557],
       [0.78754113, 0.96900788, 0.        , 0.676317  , 0.61833409],
       [0.98588035, 0.43228805, 0.676317  , 0.        , 0.52866161],
       [0.46720887, 0.48758557, 0.61833409, 0.52866161, 0.        ]])