### Read mp4 video into a single `numpy.ndarray`

In [5]:
import skvideo.io
import skvideo.datasets

try:
    videodata = skvideo.io.vread('./data/go-cart.mp4')
    print(videodata.shape) # number_of_frames, height, width, channel
except:
    print('can not open video')
    raise

(260, 1920, 1080, 3)


### Read mp4 the first 5 frames from a video into a single `numpy.ndarray`

In [8]:
import skvideo.io
import skvideo.datasets

try:
    videodata = skvideo.io.vread('./data/go-cart.mp4', num_frames=5)
    print(videodata.shape)
except:
    print('can not open video')
    raise

(5, 1920, 1080, 3)


### Read mp4 video into a single 'numpy.ndarray', then write to a mp4 video

In [7]:
import skvideo.io
import skvideo.datasets

try:
    videodata = skvideo.io.vread('./data/go-cart.mp4')
    print(videodata.shape)
    try:
        skvideo.io.vwrite('./data/go-cart-written.mp4', videodata)
    except:
        print('Fail to write video')
        raise
except:
    print('Fail to open video')
    raise

(260, 1920, 1080, 3)


### Read mp4 video frame-by-frame

In [10]:
import skvideo.io
import skvideo.datasets

try:
    videogen = skvideo.io.vreader('./data/go-cart.mp4', num_frames=5)
    
    for frame in videogen:
        print(frame.shape)    
except:
    print('can not open video')
    raise

(1920, 1080, 3)
(1920, 1080, 3)
(1920, 1080, 3)
(1920, 1080, 3)
(1920, 1080, 3)


### Read mp4 video frame-by-frame, downsample, write out to a mp4 video

In [69]:
import skvideo.io
import skvideo.datasets

downsample_rate = 3

try:
    writer = skvideo.io.FFmpegWriter("./data/go-cart-downsampled-by-3.mp4")
    
    try:
        #videogen = skvideo.io.vreader('./data/go-cart.mp4', num_frames=200)
        videogen = skvideo.io.vreader('./data/go-cart.mp4')

        for i, frame in enumerate(videogen):
            if i%downsample_rate == 0:
                #print(i)
                #print(frame.shape)    
                writer.writeFrame(frame)
        writer.close()
        print('downsampled, and written out')
    except:
        print('fail to open video')
        raise
except:
    print('Fail to open output file')

downsampled, and written out


### `downsample` function

In [84]:
def downsample(downsample_rate, infile, outfile):
    import skvideo.io
    import skvideo.datasets

    try:
        writer = skvideo.io.FFmpegWriter(outfile)

        try:
            #videogen = skvideo.io.vreader('./data/go-cart.mp4', num_frames=200)
            videogen = skvideo.io.vreader(infile)

            for i, frame in enumerate(videogen):
                if i%downsample_rate == 0:
                    #print(i)
                    #print(frame.shape)    
                    writer.writeFrame(frame)
            writer.close()
            print('downsampled, and written out')
        except:
            print('fail to open video')
            raise
    except:
        print('Fail to open output file')    
        
    return 

In [85]:
downsample(downsample_rate=3, infile="./data/go-cart.mp4", outfile="./data/go-cart-downsampled-by-3.mp4")

downsampled, and written out


In [41]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np

a = np.array([1, 2, 3]); a.shape
b = np.array([2, 3, 4]); b.shape
c = np.vstack((a,b)); c.shape
a
z = np.empty_like(a); z
d = np.vstack((z,a)); d.shape; d

(3,)

(3,)

(2, 3)

array([1, 2, 3])

array([2, 3, 4])

(2, 3)

array([[2, 3, 4],
       [1, 2, 3]])

In [47]:
a = np.array([1, 2, 3]); a.shape
b = np.array([2, 3, 4]); b.shape
c = np.concatenate((a,b)); c.shape; c

(3,)

(3,)

(6,)

array([1, 2, 3, 2, 3, 4])

In [52]:
a = np.array([1, 2, 3]); a.shape
b = np.array([2, 3, 4]); b.shape
z = np.((3,)); z
d = np.concatenate((z,a)); d.shape; d

(3,)

(3,)

AttributeError: module 'numpy' has no attribute 'na'