In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [63]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

## Add `datetime` to a 2D numpy array

In [8]:
trade_type = np.dtype(
[
    ('id', 'U'),
    ('timestamp', 'u8'),
    ('datetime', np.dtype('datetime64[s]'))
]
)

array = np.zeros(shape=(3,1), dtype=trade_type)
array['datetime'] = np.datetime64('1970-01-01 00:00:00')

In [9]:
array

array([[('', 0, '1970-01-01T00:00:00')],
       [('', 0, '1970-01-01T00:00:00')],
       [('', 0, '1970-01-01T00:00:00')]],
      dtype=[('id', '<U'), ('timestamp', '<u8'), ('datetime', '<M8[s]')])

## Create a column of `datetime` in 2D numpy array 
### using `datetime.datetime` and `datetime.timedelta`

In [33]:
base = datetime(2000, 1, 1)
arr1 = np.array([base + timedelta(hours=i) for i in range(5)])

### using `np.datetime64` and `np.timedelta64`

In [35]:
base = np.datetime64('2020-01-15')
arr2 = np.array([base + np.timedelta64(i, 'D') for i in range(5)]).reshape((5,1))
arr2 

array([['2020-01-15'],
       ['2020-01-16'],
       ['2020-01-17'],
       ['2020-01-18'],
       ['2020-01-19']], dtype='datetime64[D]')

### using `np.arange`

In [43]:
arr3 = np.arange('2020-01-15', '2020-01-20', dtype='datetime64[D]').reshape((5,1))
arr3

array([['2020-01-15'],
       ['2020-01-16'],
       ['2020-01-17'],
       ['2020-01-18'],
       ['2020-01-19']], dtype='datetime64[D]')

## Add `datetime` to a 3D numpy array
- ref: https://numpy.org/doc/stable/reference/arrays.dtypes.html

In [58]:
arr_3D_dtype = np.dtype(
    [
        ('sku', np.dtype(int)),
        ('location', np.dtype(int)),
        ('datetime', np.dtype('datetime64[s]'))
    ]
)

arr_3D = np.zeros(shape=(2,3,5), dtype=arr_3D_dtype)
arr_3D['datetime'] = np.datetime64('1970-01-01 00:00:00')
arr_3D

array([[[(0, 0, '1970-01-01T00:00:00'), (0, 0, '1970-01-01T00:00:00'),
         (0, 0, '1970-01-01T00:00:00'), (0, 0, '1970-01-01T00:00:00'),
         (0, 0, '1970-01-01T00:00:00')],
        [(0, 0, '1970-01-01T00:00:00'), (0, 0, '1970-01-01T00:00:00'),
         (0, 0, '1970-01-01T00:00:00'), (0, 0, '1970-01-01T00:00:00'),
         (0, 0, '1970-01-01T00:00:00')],
        [(0, 0, '1970-01-01T00:00:00'), (0, 0, '1970-01-01T00:00:00'),
         (0, 0, '1970-01-01T00:00:00'), (0, 0, '1970-01-01T00:00:00'),
         (0, 0, '1970-01-01T00:00:00')]],

       [[(0, 0, '1970-01-01T00:00:00'), (0, 0, '1970-01-01T00:00:00'),
         (0, 0, '1970-01-01T00:00:00'), (0, 0, '1970-01-01T00:00:00'),
         (0, 0, '1970-01-01T00:00:00')],
        [(0, 0, '1970-01-01T00:00:00'), (0, 0, '1970-01-01T00:00:00'),
         (0, 0, '1970-01-01T00:00:00'), (0, 0, '1970-01-01T00:00:00'),
         (0, 0, '1970-01-01T00:00:00')],
        [(0, 0, '1970-01-01T00:00:00'), (0, 0, '1970-01-01T00:00:00'),
         (0,

In [47]:
arr_3D = np.zeros((2,3,5)); print(arr_3D)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [48]:
arr_3D[:,:,3] = arr3[0]
arr_3D

array([[[    0.,     0.,     0., 18276.,     0.],
        [    0.,     0.,     0., 18276.,     0.],
        [    0.,     0.,     0., 18276.,     0.]],

       [[    0.,     0.,     0., 18276.,     0.],
        [    0.,     0.,     0., 18276.,     0.],
        [    0.,     0.,     0., 18276.,     0.]]])

In [ ]:
----------

In [66]:
a = np.random.randint(0,9,(2,3,5)); a

array([[[3, 7, 4, 5, 3],
        [2, 7, 1, 6, 3],
        [8, 1, 4, 8, 1]],

       [[3, 0, 3, 6, 1],
        [0, 8, 5, 7, 1],
        [6, 5, 3, 4, 0]]])

In [68]:
d1,d2,d3 = a.shape; d1,d2,d3
out_arr = np.column_stack((np.repeat(np.arange(d1),d2),a.reshape(d1*d2,-1))); out_arr
out_df = pd.DataFrame(out_arr); out_df

(2, 3, 5)

array([[0, 3, 7, 4, 5, 3],
       [0, 2, 7, 1, 6, 3],
       [0, 8, 1, 4, 8, 1],
       [1, 3, 0, 3, 6, 1],
       [1, 0, 8, 5, 7, 1],
       [1, 6, 5, 3, 4, 0]])

0  1  2  3  4  5
0  0  3  7  4  5  3
1  0  2  7  1  6  3
2  0  8  1  4  8  1
3  1  3  0  3  6  1
4  1  0  8  5  7  1
5  1  6  5  3  4  0

In [70]:
a.reshape(d1*d2,-1)

array([[3, 7, 4, 5, 3],
       [2, 7, 1, 6, 3],
       [8, 1, 4, 8, 1],
       [3, 0, 3, 6, 1],
       [0, 8, 5, 7, 1],
       [6, 5, 3, 4, 0]])

In [72]:
pd.DataFrame(a.reshape(d1*d2,-1))

0  1  2  3  4
0  3  7  4  5  3
1  2  7  1  6  3
2  8  1  4  8  1
3  3  0  3  6  1
4  0  8  5  7  1
5  6  5  3  4  0