In [3]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [7]:
x = np.array([[1, 3, 6, 10], [0, 5, 6, 8]]); x.shape; x
np.diff(x)

(2, 4)

array([[ 1,  3,  6, 10],
       [ 0,  5,  6,  8]])

array([[2, 3, 4],
       [5, 1, 2]])

In [6]:
np.diff(x, axis=1)

array([[2, 3, 4],
       [5, 1, 2]])

In [5]:
np.diff(x, axis=0)

array([[-1,  2,  0, -2]])