In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np
from sklearn.model_selection import TimeSeriesSplit

In [3]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
y = np.array([1, 2, 3, 4, 5, 6])

tscv = TimeSeriesSplit(n_splits=5)

for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [0] TEST: [1]
TRAIN: [0 1] TEST: [2]
TRAIN: [0 1 2] TEST: [3]
TRAIN: [0 1 2 3] TEST: [4]
TRAIN: [0 1 2 3 4] TEST: [5]


In [4]:
tscv = TimeSeriesSplit(n_splits=4)

for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [0 1] TEST: [2]
TRAIN: [0 1 2] TEST: [3]
TRAIN: [0 1 2 3] TEST: [4]
TRAIN: [0 1 2 3 4] TEST: [5]


In [5]:
tscv = TimeSeriesSplit(n_splits=3)

for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [0 1 2] TEST: [3]
TRAIN: [0 1 2 3] TEST: [4]
TRAIN: [0 1 2 3 4] TEST: [5]


In [6]:
tscv = TimeSeriesSplit(n_splits=2)

for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [0 1] TEST: [2 3]
TRAIN: [0 1 2 3] TEST: [4 5]


### Tutorial

In [7]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
y = np.array([1, 2, 3, 4, 5, 6])

X.shape
X
y.shape
y

(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

(6,)

array([1, 2, 3, 4, 5, 6])

### `n_splits=2`

In [8]:
tscv = TimeSeriesSplit(n_splits=2)
print(tscv)

for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    print("TRAIN ............")
    X_train, X_test = X[train_index], X[test_index]
    X_train.shape, X_test.shape
    X_train, X_test
    
    print("TEST ............")
    y_train, y_test = y[train_index], y[test_index]
    y_train.shape, y_test.shape
    y_train, y_test

TimeSeriesSplit(max_train_size=None, n_splits=2)
TRAIN: [0 1] TEST: [2 3]
TRAIN ............


((2, 2), (2, 2))

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

TEST ............


((2,), (2,))

(array([1, 2]), array([3, 4]))

TRAIN: [0 1 2 3] TEST: [4 5]
TRAIN ............


((4, 2), (2, 2))

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]]))

TEST ............


((4,), (2,))

(array([1, 2, 3, 4]), array([5, 6]))

### `n_splits=5`

In [9]:
tscv = TimeSeriesSplit(n_splits=5)
print(tscv)

for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    print("TRAIN ............")
    X_train, X_test = X[train_index], X[test_index]
    #print('X_train.shape, X_test.shape: ', X_train.shape, X_test.shape)
    X_train, X_test
    
    print("TEST ............")
    y_train, y_test = y[train_index], y[test_index]
   #y_train.shape, y_test.shape
    y_train, y_test

TimeSeriesSplit(max_train_size=None, n_splits=5)
TRAIN: [0] TEST: [1]
TRAIN ............


(array([[1, 2]]), array([[3, 4]]))

TEST ............


(array([1]), array([2]))

TRAIN: [0 1] TEST: [2]
TRAIN ............


(array([[1, 2],
        [3, 4]]),
 array([[5, 6]]))

TEST ............


(array([1, 2]), array([3]))

TRAIN: [0 1 2] TEST: [3]
TRAIN ............


(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[7, 8]]))

TEST ............


(array([1, 2, 3]), array([4]))

TRAIN: [0 1 2 3] TEST: [4]
TRAIN ............


(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[ 9, 10]]))

TEST ............


(array([1, 2, 3, 4]), array([5]))

TRAIN: [0 1 2 3 4] TEST: [5]
TRAIN ............


(array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]),
 array([[11, 12]]))

TEST ............


(array([1, 2, 3, 4, 5]), array([6]))

### Get the last element of generator

In [10]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
y = np.array([1, 2, 3, 4, 5, 6])

tscv = TimeSeriesSplit(n_splits=5)

for train_index, test_index in list(tscv.split(X))[-1:]: # Get the last element of generator
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [0 1 2 3 4] TEST: [5]


### Splitting 3D array

In [11]:
X_3D = np.array([[[111, 112, 113, 114, 115],
                  [121, 122, 123, 124, 125],
                  [131, 132, 133, 134, 135]],
                 [[211, 212, 213, 214, 215],
                  [221, 222, 223, 224, 225],
                  [231, 232, 233, 234, 235]]])

# Get the shape of 3D array
print('********** d_sku,d_loc,d_day **********')
d_sku,d_loc,d_day = X_3D.shape; d_sku,d_loc,d_day 

# for each SKU
for s in range(d_sku):
    # extract the LOC x DAY 
    print('***** X_2D : LOC x DAY ******')
    X_2D = X_3D[s,:,:]; X_2D.shape; X_2D
    
    print('******* X_2D.T :  DAY x LOC *******')
    X_2D.T
    
    # Create a TimeSeriesSplit
    n_splits = d_day-1; n_splits
    tscv = TimeSeriesSplit(n_splits=n_splits)

    # for each split
    for train_index, test_index in tscv.split(X_2D.T): # transpose to DAY x LOC
        print("TRAIN:", train_index, "TEST:", test_index)
        X_train, X_test = X_2D.T[train_index].T, X_2D.T[test_index].T # do the split, and transpose back to LOC x DAY
        #X_train.shape, X_test.shape
        print('X_train: \n', X_train)
        print('X_test: \n', X_test)

********** d_sku,d_loc,d_day **********


(2, 3, 5)

***** X_2D : LOC x DAY ******


(3, 5)

array([[111, 112, 113, 114, 115],
       [121, 122, 123, 124, 125],
       [131, 132, 133, 134, 135]])

******* X_2D.T :  DAY x LOC *******


array([[111, 121, 131],
       [112, 122, 132],
       [113, 123, 133],
       [114, 124, 134],
       [115, 125, 135]])

4

TRAIN: [0] TEST: [1]
X_train: 
 [[111]
 [121]
 [131]]
X_test: 
 [[112]
 [122]
 [132]]
TRAIN: [0 1] TEST: [2]
X_train: 
 [[111 112]
 [121 122]
 [131 132]]
X_test: 
 [[113]
 [123]
 [133]]
TRAIN: [0 1 2] TEST: [3]
X_train: 
 [[111 112 113]
 [121 122 123]
 [131 132 133]]
X_test: 
 [[114]
 [124]
 [134]]
TRAIN: [0 1 2 3] TEST: [4]
X_train: 
 [[111 112 113 114]
 [121 122 123 124]
 [131 132 133 134]]
X_test: 
 [[115]
 [125]
 [135]]
***** X_2D : LOC x DAY ******


(3, 5)

array([[211, 212, 213, 214, 215],
       [221, 222, 223, 224, 225],
       [231, 232, 233, 234, 235]])

******* X_2D.T :  DAY x LOC *******


array([[211, 221, 231],
       [212, 222, 232],
       [213, 223, 233],
       [214, 224, 234],
       [215, 225, 235]])

4

TRAIN: [0] TEST: [1]
X_train: 
 [[211]
 [221]
 [231]]
X_test: 
 [[212]
 [222]
 [232]]
TRAIN: [0 1] TEST: [2]
X_train: 
 [[211 212]
 [221 222]
 [231 232]]
X_test: 
 [[213]
 [223]
 [233]]
TRAIN: [0 1 2] TEST: [3]
X_train: 
 [[211 212 213]
 [221 222 223]
 [231 232 233]]
X_test: 
 [[214]
 [224]
 [234]]
TRAIN: [0 1 2 3] TEST: [4]
X_train: 
 [[211 212 213 214]
 [221 222 223 224]
 [231 232 233 234]]
X_test: 
 [[215]
 [225]
 [235]]


### Recontruct back to original dimensionality

##### Tutorial

In [13]:
a = np.array([['L0-S0-D0', 'L0-S0-D1', 'L0-S0-D2', 'L0-S0-D3'],
              ['L1-S0-D0', 'L1-S0-D1', 'L1-S0-D2', 'L1-S0-D3'],
              ['L2-S0-D0', 'L2-S0-D1', 'L2-S0-D2', 'L2-S0-D3']]); a.shape #[LOC x DAY], i.e. (3,4)

b = np.array([['L0-S1-D0', 'L0-S1-D1', 'L0-S1-D2', 'L0-S1-D3'],
              ['L1-S1-D0', 'L1-S1-D1', 'L1-S1-D2', 'L1-S1-D3'],
              ['L2-S1-D0', 'L2-S1-D1', 'L2-S1-D2', 'L2-S1-D3']]); b.shape #[LOC x DAY], i.e. (3,4)

c = np.stack((a,b), axis=1) 
c.shape # [LOC x SKU x DAY] , i.e. (3, 2, 4)
c

(3, 4)

(3, 4)

(3, 2, 4)

array([[['L0-S0-D0', 'L0-S0-D1', 'L0-S0-D2', 'L0-S0-D3'],
        ['L0-S1-D0', 'L0-S1-D1', 'L0-S1-D2', 'L0-S1-D3']],

       [['L1-S0-D0', 'L1-S0-D1', 'L1-S0-D2', 'L1-S0-D3'],
        ['L1-S1-D0', 'L1-S1-D1', 'L1-S1-D2', 'L1-S1-D3']],

       [['L2-S0-D0', 'L2-S0-D1', 'L2-S0-D2', 'L2-S0-D3'],
        ['L2-S1-D0', 'L2-S1-D1', 'L2-S1-D2', 'L2-S1-D3']]], dtype='<U8')

### Make into a function
- input: 2D or 3D array `X`, number of splits `n_splits`
- return `dict` of `dict`

In [13]:
from sklearn.model_selection import TimeSeriesSplit

def split_it(d, train_test_splits, X_2D, tscv):
    
    # key for first level dict
    key_sku = str(d) # first dimention (e.g. sku)

    # first level dict
    train_test_splits[key_sku] = {}

    # for each split
    for i, [train_index, test_index] in enumerate(tscv.split(X_2D.T)): # transpose from STEP x LOC
        X_train, X_test = X_2D.T[train_index].T, X_2D.T[test_index].T # do the split, and transpose back to STEP x DAY

        # key for 2nd level dictionary
        key_split_n = str(i)  # split_n

        # add to dict of dicts
        train_test_splits[key_sku][key_split_n] = {'X_train': X_train, 'X_test': X_test}

    return (train_test_splits)

def time_series_split(X, n_splits):
    '''
    input: ndarray X of [LOC x SKU x STEP] or [SKU x STEP]
    output: a dictionary consist of n_splits
    '''
    # Create a dict to hold the splits
    train_test_splits = {} # dict of dicts 

    # Create a TimeSeriesSplit
    tscv = TimeSeriesSplit(n_splits=n_splits)

    ### if X is [SKU x STEP]
    if len(X.shape) == 2:
        
        # reshape to [1 x SKU x STEP]
        X1 = X.copy()
        X = X1.reshape((1, X.shape[0], X.shape[1]))  # [LOC=1 x SKU x STEP]
      
    ### If X is [LOC x SKU x STEP]
    if len(X.shape) == 3:
        # transpose from [LOC x SKU x DAY] to [SKU x LOC x DAY]
        X = np.transpose(X, (1,0,2)); 
        
        # Get the shape of 3D array
        d1,d2,d3 = X.shape

        # for each d1, i.e. SKU
        for d in range(d1):
            # extract the LOC x STEP
            X_2D = X[d,:,:]; X_2D
        
            train_test_splits = split_it(d=d, train_test_splits=train_test_splits, X_2D=X_2D, tscv=tscv)
   
    return(train_test_splits)

def reconstruct(n_splits, n_sku, train_test_splits):
    train_test_split_reconstruct = {}

    # for each split
    for split in range(n_splits):
        stack_train = []
        stack_test = []
        
        # create dict using `split` as key
        key_split = str(split)
        train_test_split_reconstruct[key_split] = {}
        
        # for each sku
        for sku in range(n_sku): # sku index
            # append into a list
            stack_train.append(train_test_splits[str(sku)][str(split)]['X_train']) #[LOC x DAY]
            stack_test.append(train_test_splits[str(sku)][str(split)]['X_test']) #[LOC x DAY]
            # stack and convert into numpy array
            train_stacked = np.stack(stack_train, axis=1) # [LOC x SKU x DAY]
            test_stacked = np.stack(stack_test, axis=1) # [LOC x SKU x DAY]

        # put into dict
        train_test_split_reconstruct[key_split]['X_train'] = train_stacked
        train_test_split_reconstruct[key_split]['X_test'] = test_stacked
        
    return(train_test_split_reconstruct)

#### use case 1: `[LOC, SKU, DAY]`

In [21]:
X_3D = np.array([[[111, 112, 113, 114],
                  [121, 122, 123, 124]],
                 [[211, 212, 213, 214],
                  [221, 222, 223, 224]],
                 [[311, 312, 313, 314],
                  [321, 322, 323, 324]]])

X_3D.shape; X_3D

n_splits = X_3D.shape[-1]-1; n_splits

#train_test_splits = time_series_split(X_3DT, n_splits=n_splits)
train_test_splits = time_series_split(X_3D, n_splits=n_splits)

(3, 2, 4)

array([[[111, 112, 113, 114],
        [121, 122, 123, 124]],

       [[211, 212, 213, 214],
        [221, 222, 223, 224]],

       [[311, 312, 313, 314],
        [321, 322, 323, 324]]])

3

In [23]:
train_test_splits

{'0': {'0': {'X_train': array([[111],
          [211],
          [311]]),
   'X_test': array([[112],
          [212],
          [312]])},
  '1': {'X_train': array([[111, 112],
          [211, 212],
          [311, 312]]),
   'X_test': array([[113],
          [213],
          [313]])},
  '2': {'X_train': array([[111, 112, 113],
          [211, 212, 213],
          [311, 312, 313]]),
   'X_test': array([[114],
          [214],
          [314]])}},
 '1': {'0': {'X_train': array([[121],
          [221],
          [321]]),
   'X_test': array([[122],
          [222],
          [322]])},
  '1': {'X_train': array([[121, 122],
          [221, 222],
          [321, 322]]),
   'X_test': array([[123],
          [223],
          [323]])},
  '2': {'X_train': array([[121, 122, 123],
          [221, 222, 223],
          [321, 322, 323]]),
   'X_test': array([[124],
          [224],
          [324]])}}}

In [16]:
for sku in range(X_3D.shape[1]):
    for split in range(n_splits):
        sku, split
        print('X_train shape: ', train_test_splits[str(sku)][str(split)]['X_train'].shape) # [LOC x DAY]
        train_test_splits[str(sku)][str(split)]['X_train']  # sku, split, X_train
        print('X_test shape: ', train_test_splits[str(sku)][str(split)]['X_test'].shape) # [LOC x DAY]
        train_test_splits[str(sku)][str(split)]['X_test']  # sku, split, X_test

(0, 0)

X_train shape:  (3, 1)


array([[111],
       [211],
       [311]])

X_test shape:  (3, 1)


array([[112],
       [212],
       [312]])

(0, 1)

X_train shape:  (3, 2)


array([[111, 112],
       [211, 212],
       [311, 312]])

X_test shape:  (3, 1)


array([[113],
       [213],
       [313]])

(0, 2)

X_train shape:  (3, 3)


array([[111, 112, 113],
       [211, 212, 213],
       [311, 312, 313]])

X_test shape:  (3, 1)


array([[114],
       [214],
       [314]])

(0, 3)

X_train shape:  (3, 4)


array([[111, 112, 113, 114],
       [211, 212, 213, 214],
       [311, 312, 313, 314]])

X_test shape:  (3, 1)


array([[115],
       [215],
       [315]])

(1, 0)

X_train shape:  (3, 1)


array([[121],
       [221],
       [321]])

X_test shape:  (3, 1)


array([[122],
       [222],
       [322]])

(1, 1)

X_train shape:  (3, 2)


array([[121, 122],
       [221, 222],
       [321, 322]])

X_test shape:  (3, 1)


array([[123],
       [223],
       [323]])

(1, 2)

X_train shape:  (3, 3)


array([[121, 122, 123],
       [221, 222, 223],
       [321, 322, 323]])

X_test shape:  (3, 1)


array([[124],
       [224],
       [324]])

(1, 3)

X_train shape:  (3, 4)


array([[121, 122, 123, 124],
       [221, 222, 223, 224],
       [321, 322, 323, 324]])

X_test shape:  (3, 1)


array([[125],
       [225],
       [325]])

In [17]:
train_test_splits['1']['3']['X_train']  # sku, split, X_train
train_test_splits['1']['3']['X_test']  # sku, split, X_test

array([[121, 122, 123, 124],
       [221, 222, 223, 224],
       [321, 322, 323, 324]])

array([[125],
       [225],
       [325]])

#### Reconstruct splits back to original dimensions `[LOC, SKU, DAY]`, given all `sku`

In [24]:
train_test_split_reconstruct = reconstruct(n_splits=3, n_sku=2, train_test_splits=train_test_splits)

In [25]:
train_test_split_reconstruct

{'0': {'X_train': array([[[111],
          [121]],
  
         [[211],
          [221]],
  
         [[311],
          [321]]]),
  'X_test': array([[[112],
          [122]],
  
         [[212],
          [222]],
  
         [[312],
          [322]]])},
 '1': {'X_train': array([[[111, 112],
          [121, 122]],
  
         [[211, 212],
          [221, 222]],
  
         [[311, 312],
          [321, 322]]]),
  'X_test': array([[[113],
          [123]],
  
         [[213],
          [223]],
  
         [[313],
          [323]]])},
 '2': {'X_train': array([[[111, 112, 113],
          [121, 122, 123]],
  
         [[211, 212, 213],
          [221, 222, 223]],
  
         [[311, 312, 313],
          [321, 322, 323]]]),
  'X_test': array([[[114],
          [124]],
  
         [[214],
          [224]],
  
         [[314],
          [324]]])}}

#### Accessing `train_test_split_reconstruct`

In [19]:
n_split = 3
train_test_split_reconstruct[str(n_split)]['X_train']
train_test_split_reconstruct[str(n_split)]['X_test']

array([[[111, 112, 113, 114],
        [121, 122, 123, 124]],

       [[211, 212, 213, 214],
        [221, 222, 223, 224]],

       [[311, 312, 313, 314],
        [321, 322, 323, 324]]])

array([[[115],
        [125]],

       [[215],
        [225]],

       [[315],
        [325]]])

#### use case 2: `[SKU, DAY]`

In [26]:
X_2D = np.array([[111, 112, 113, 114],
                 [121, 122, 123, 124],
                 [131, 132, 133, 134]])
X_2D.shape
X_2D

(3, 4)

array([[111, 112, 113, 114],
       [121, 122, 123, 124],
       [131, 132, 133, 134]])

In [27]:
n_splits = 3

train_test_splits = time_series_split(X_2D, n_splits=n_splits)

In [28]:
train_test_splits

{'0': {'0': {'X_train': array([[111]]), 'X_test': array([[112]])},
  '1': {'X_train': array([[111, 112]]), 'X_test': array([[113]])},
  '2': {'X_train': array([[111, 112, 113]]), 'X_test': array([[114]])}},
 '1': {'0': {'X_train': array([[121]]), 'X_test': array([[122]])},
  '1': {'X_train': array([[121, 122]]), 'X_test': array([[123]])},
  '2': {'X_train': array([[121, 122, 123]]), 'X_test': array([[124]])}},
 '2': {'0': {'X_train': array([[131]]), 'X_test': array([[132]])},
  '1': {'X_train': array([[131, 132]]), 'X_test': array([[133]])},
  '2': {'X_train': array([[131, 132, 133]]), 'X_test': array([[134]])}}}

#### Reconstruct splits back to original dimensions `[SKU, DAY]`, given all `sku`

In [30]:
train_test_split_reconstruct = reconstruct(n_splits=3, n_sku=2, train_test_splits=train_test_splits)

In [32]:
train_test_split_reconstruct

{'0': {'X_train': array([[[111],
          [121]]]),
  'X_test': array([[[112],
          [122]]])},
 '1': {'X_train': array([[[111, 112],
          [121, 122]]]),
  'X_test': array([[[113],
          [123]]])},
 '2': {'X_train': array([[[111, 112, 113],
          [121, 122, 123]]]),
  'X_test': array([[[114],
          [124]]])}}

#### Accessing `train_test_split_reconstruct`

In [47]:
n_split = 2
train_test_split_reconstruct[str(n_split)]['X_train']
train_test_split_reconstruct[str(n_split)]['X_test']

array([[[111, 112, 113],
        [121, 122, 123]]])

array([[[114],
        [124]]])

#### use case 3: `[1, SKU, DAY]`

In [33]:
X_2D = np.array([[111, 112, 113, 114],
                 [121, 122, 123, 124],
                 [131, 132, 133, 134]])
X_2D.shape

X_3D = X_2D.reshape(1, X_2D.shape[0], X_2D.shape[1])
X_3D.shape
X_3D

n_splits = X_3D.shape[-1]-1; n_splits

(3, 4)

(1, 3, 4)

array([[[111, 112, 113, 114],
        [121, 122, 123, 124],
        [131, 132, 133, 134]]])

3

In [34]:
train_test_splits = time_series_split(X_3D, n_splits=n_splits)

In [35]:
train_test_splits

{'0': {'0': {'X_train': array([[111]]), 'X_test': array([[112]])},
  '1': {'X_train': array([[111, 112]]), 'X_test': array([[113]])},
  '2': {'X_train': array([[111, 112, 113]]), 'X_test': array([[114]])}},
 '1': {'0': {'X_train': array([[121]]), 'X_test': array([[122]])},
  '1': {'X_train': array([[121, 122]]), 'X_test': array([[123]])},
  '2': {'X_train': array([[121, 122, 123]]), 'X_test': array([[124]])}},
 '2': {'0': {'X_train': array([[131]]), 'X_test': array([[132]])},
  '1': {'X_train': array([[131, 132]]), 'X_test': array([[133]])},
  '2': {'X_train': array([[131, 132, 133]]), 'X_test': array([[134]])}}}

In [37]:
train_test_splits['1']['2']['X_train']  # sku, split, X_train
train_test_splits['1']['2']['X_test']  # sku, split, X_test

array([[121, 122, 123]])

array([[124]])

In [38]:
X_3D.shape

for sku in range(X_3D.shape[1]):
    for split in range(n_splits):
        sku, split
        print('X_train shape: ', train_test_splits[str(sku)][str(split)]['X_train'].shape) # [LOC x DAY]
        train_test_splits[str(sku)][str(split)]['X_train']  # sku, split, X_train
        print('X_test shape: ', train_test_splits[str(sku)][str(split)]['X_test'].shape) # [LOC x DAY]
        train_test_splits[str(sku)][str(split)]['X_test']  # sku, split, X_test

(1, 3, 4)

(0, 0)

X_train shape:  (1, 1)


array([[111]])

X_test shape:  (1, 1)


array([[112]])

(0, 1)

X_train shape:  (1, 2)


array([[111, 112]])

X_test shape:  (1, 1)


array([[113]])

(0, 2)

X_train shape:  (1, 3)


array([[111, 112, 113]])

X_test shape:  (1, 1)


array([[114]])

(1, 0)

X_train shape:  (1, 1)


array([[121]])

X_test shape:  (1, 1)


array([[122]])

(1, 1)

X_train shape:  (1, 2)


array([[121, 122]])

X_test shape:  (1, 1)


array([[123]])

(1, 2)

X_train shape:  (1, 3)


array([[121, 122, 123]])

X_test shape:  (1, 1)


array([[124]])

(2, 0)

X_train shape:  (1, 1)


array([[131]])

X_test shape:  (1, 1)


array([[132]])

(2, 1)

X_train shape:  (1, 2)


array([[131, 132]])

X_test shape:  (1, 1)


array([[133]])

(2, 2)

X_train shape:  (1, 3)


array([[131, 132, 133]])

X_test shape:  (1, 1)


array([[134]])

#### Reconstruct splits back to original dimensions `[1, SKU, DAY]`, given all `sku`

In [41]:
train_test_split_reconstruct = reconstruct(n_splits=3, n_sku=2, train_test_splits=train_test_splits)

In [42]:
train_test_split_reconstruct

{'0': {'X_train': array([[[111],
          [121]]]),
  'X_test': array([[[112],
          [122]]])},
 '1': {'X_train': array([[[111, 112],
          [121, 122]]]),
  'X_test': array([[[113],
          [123]]])},
 '2': {'X_train': array([[[111, 112, 113],
          [121, 122, 123]]]),
  'X_test': array([[[114],
          [124]]])}}

#### Accessing `train_test_split_reconstruct`

In [44]:
n_split = 2
train_test_split_reconstruct[str(n_split)]['X_train']
train_test_split_reconstruct[str(n_split)]['X_test']

array([[[111, 112, 113],
        [121, 122, 123]]])

array([[[114],
        [124]]])